### ISSUE TITLE
Clicking on year 2018 throws an "Internal Server Error"

### ISSUE THREAD

**Issue by mfrancis95** [ComputerScienceHouse/profiles#48]

**Comment by stevenmirabito** [comment]
Traceback from logs:

```
ERROR:flask.app:Exception on /year/2018 [GET]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
TypeError: 'CSHMember' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/flask_pyoidc/flask_pyoidc.py", line 253, in wrapper
    return view_func(*args, **kwargs)
  File "/opt/app-root/src/profiles/utils.py", line 42, in wrapped_function
    return func(*args, **kwargs)
  File "/opt/app-root/src/profiles/__init__.py", line 113, in year
    members=ldap_get_year(_year))
  File "/opt/app-root/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/opt/app-root/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/app-root/src/profiles/templates/listing.html", line 14, in top-level template code
    <a href="/user/{{ m['uid'] }}" class="profile-link">
  File "/opt/app-root/lib/python3.6/site-packages/jinja2/environment.py", line 420, in getitem
    return getattr(obj, attr)
  File "/opt/app-root/lib/python3.6/site-packages/csh_ldap/member.py", line 89, in __getattr__
    return res[0][1][key][0].decode('utf-8')
IndexError: list index out of range
```

**Comment by evelyndooley** [comment]
Looking into it after work when I can get on cshnet. This issue only happens to the year 2018. Every year (past and future) works as intended with no error. There might be some weird attribute in LDAP causing it to crash.

**Comment by mfrancis95** [comment]
It's working now.
